@include('admin.includes.head')
@include('admin.includes.sidebar')
@include('admin.includes.header')
@include('admin.includes.messages')
@include('admin.includes.compose')
@yield('content')
@include('admin.includes.footer')